nfpms:
  - id: packages
    package_name: nmsmods
    maintainer: "nmsmods maintainers"
    description: "Safe-by-default mod manager for No Man’s Sky on Linux (Steam/Proton)"
    license: "MIT"
    formats:
      - deb
    bindir: /usr/bin

    depends:
      - xdg-utils

    contents:
      # Desktop entry for nxm:// handler
      - src: packaging/nmsmods.desktop
        dst: /usr/share/applications/nmsmods.desktop
        file_info:
          mode: 0644

      # Bash completion
      - src: completions/nmsmods.bash
        dst: /usr/share/bash-completion/completions/nmsmods
        file_info:
          mode: 0644

      # Zsh completion
      - src: completions/_nmsmods
        dst: /usr/share/zsh/site-functions/_nmsmods
        file_info:
          mode: 0644

      # Fish completion
      - src: completions/nmsmods.fish
        dst: /usr/share/fish/vendor_completions.d/nmsmods.fish
        file_info:
          mode: 0644

    scripts:
      postinstall: packaging/deb/postinstall.sh
      preremove: packaging/deb/preremove.sh