version: 2

project_name: nmsmods

before:
  hooks:
    - go mod tidy
    - mkdir -p completions
    - sh -c "go run . completion bash > completions/nmsmods.bash"
    - sh -c "go run . completion zsh  > completions/_nmsmods"
    - sh -c "go run . completion fish > completions/nmsmods.fish"

builds:
  - id: nmsmods
    main: .
    binary: nmsmods
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -X nmsmods/internal/app.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - completions/*

checksum:
  name_template: "checksums.txt"

sboms:
  - artifacts: archive

nfpms:
  - id: packages
    package_name: nmsmods
    maintainer: "nmsmods maintainers"
    description: "Safe-by-default mod manager for No Man’s Sky on Linux (Steam/Proton)"
    license: "MIT"
    formats:
      - deb
    bindir: /usr/bin

    dependencies:
      - xdg-utils

    contents:
      - src: packaging/nmsmods.desktop
        dst: /usr/share/applications/nmsmods.desktop
        file_info:
          mode: 0644

      - src: completions/nmsmods.bash
        dst: /usr/share/bash-completion/completions/nmsmods
        file_info:
          mode: 0644

      - src: completions/_nmsmods
        dst: /usr/share/zsh/site-functions/_nmsmods
        file_info:
          mode: 0644

      - src: completions/nmsmods.fish
        dst: /usr/share/fish/vendor_completions.d/nmsmods.fish
        file_info:
          mode: 0644

    scripts:
      postinstall: packaging/deb/postinstall.sh
      preremove: packaging/deb/preremove.sh
release:
  draft: false
  prerelease: false