# .goreleaser.yaml
version: 2

project_name: nmsmods

before:
  hooks:
    - go mod tidy

    # Generate shell completions (requires Cobra 'completion' command)
    # Use 'go run .' so we don't depend on a prebuilt binary in hooks.
    - mkdir -p completions
    - sh -c "go run . completion bash > completions/nmsmods.bash"
    - sh -c "go run . completion zsh  > completions/_nmsmods"
    - sh -c "go run . completion fish > completions/nmsmods.fish"

builds:
  - id: nmsmods
    main: .
    binary: nmsmods
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -X nmsmods/internal/app.Version={{ .Version }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - completions/*

checksum:
  name_template: "checksums.txt"

# Ship a source tarball (useful for distro packagers and reproducible builds)
source:
  enabled: true

# SBOM for archives (supply-chain tooling)
sboms:
  - artifacts: archive

nfpms:
  - id: packages
    package_name: nmsmods
    maintainer: "nmsmods maintainers"
    description: "Safe-by-default mod manager for No Man’s Sky on Linux (Steam/Proton)"
    license: "MIT"
    formats:
      - deb
    bindir: /usr/bin

    # Install shell completions in standard locations
    contents:
      - src: completions/nmsmods.bash
        dst: /usr/share/bash-completion/completions/nmsmods
        file_info:
          mode: 0644
      - src: completions/_nmsmods
        dst: /usr/share/zsh/site-functions/_nmsmods
        file_info:
          mode: 0644
      - src: completions/nmsmods.fish
        dst: /usr/share/fish/vendor_completions.d/nmsmods.fish
        file_info:
          mode: 0644

release:
  draft: false
  prerelease: false

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"